#!/usr/bin/env bash
#Bash script that configures a new Ubuntu machine to HAproxy
sudo apt-get update
sudo apt-get -y install software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-2.0
sudo apt-get update
sudo apt-get -y install haproxy=2.0.\*
sudo sed -i '35 a \\nfrontend http_front\n\tbind *:80\n\tmode http\n\tdefault_backend http_back' /etc/haproxy/haproxy.cfg
sudo sed -i '40 a \\nbackend http_back\n\tbalance roundrobin\n\tserver web-01 35.229.98.15:80 check\n\tserver web-02 34.74.173.125:80 check' /etc/haproxy/haproxy.cfg
sudo service haproxy restart
