#!/usr/bin/env bash
# Configure my Nginx server so that /redirect_me is redirecting to another page.
REDLINK="\\\tlocation /redirect_me {\n\t\t return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n\t}\n"
apt-get update
apt-get -y install nginx
sed -i '0,/listen .*/s//listen 80 default_server;/' /etc/nginx/sites-available/default
echo "Holberton School" > /var/www/html/index.nginx-debian.html
sed -i "49i $REDLINK" /etc/nginx/sites-available/default
service nginx restart
