#!/usr/bin/env bash
# Configure my Nginx server so that /redirect_me is redirecting to another page.
apt-get -y update
apt-get -y install nginx
sudo echo 'Holberton School' | sudo tee /var/www/html/index.nginx-debian.html
service nginx start
sudo sed -i "/listen 80 default_server;/a rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;" /etc/nginx/sites-available/default
echo "Ceci n'est pas une page" > /usr/share/nginx/html/custom_404.html
sudo sed -i '/server_name _;/a error_page 404 /custom_404.html;\nlocation = /custom_404.html {\nroot /usr/share/nginx/html;\ninternal;\n}' /etc/nginx/sites-available/default
sudo service nginx restart
